# Generated by Django 3.2 on 2021-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0002_remove_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='join',
            field=models.ManyToManyField(related_name='join_trip', to='belt_exam_app.User'),
        ),
    ]
